[package]
name = "config_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
maple_core = { path = "../maple_core" }
toml = "0.5"
syn = { version = "1", features = ["full"] }
quote = "1"
serde = { version = "1", features = ["derive"] }
proc-macro2 = "1.0"
