[package]
name = "matcher"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2021"

[dependencies]
fuzzy-matcher = "0.3"
grep-matcher = "0.1"

dumb_analyzer = { path = "../dumb_analyzer" }
extracted_fzy = { path = "extracted_fzy" }
pattern = { path = "../pattern" }
types = { path = "../types" }
