[package]
name = "matcher"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
fuzzy-matcher = "0.3"

extracted_fzy = { path = "extracted_fzy" }
pattern = { path = "../pattern" }
types = { path = "../types" }
