[language.c]
highlight-name-and-groups = [
  ["comment", "Comment"],
  ["constant", "Constant"],
  ["delimiter", "Delimiter"],
  ["function", "Function"],
  ["function.special", "Special"],
  ["keyword", "Keyword"],
  ["label", "Label"],
  ["number", "Number"],
  ["operator", "Operator"],
  ["property", "SpecialKey"],
  ["string", "String"],
  ["type", "Type"],
  ["variable", "Identifier"],
]

[language.javascript]
highlight-name-and-groups = [
  ["comment", "Comment"],
  ["constant", "Constant"],
  ["constant.builtin", "Constant"],
  ["constructor", "Function"],
  ["embedded", "Function"],
  ["function", "Function"],
  ["function.builtin", "Function"],
  ["function.method", "Function"],
  ["keyword", "Keyword"],
  ["number", "Number"],
  ["operator", "Operator"],
  ["property", "SpecialKey"],
  ["punctuation.bracket", "Delimiter"],
  ["punctuation.delimiter", "Delimiter"],
  ["punctuation.special", "Delimiter"],
  ["string", "String"],
  ["string.special", "SpecialChar"],
  ["type", "Type"],
  ["variable", "Identifier"],
  ["variable.builtin", "Identifier"],
]

[language.python]
highlight-name-and-groups = [
  ["comment", "Comment"],
  ["constant", "Constant"],
  ["constant.builtin", "Constant"],
  ["constructor", "Function"],
  ["embedded", "Function"],
  ["escape", "Escape"],
  ["function", "Function"],
  ["function.builtin", "Function"],
  ["function.method", "Function"],
  ["keyword", "Keyword"],
  ["number", "Number"],
  ["operator", "Operator"],
  ["property", "Property"],
  ["punctuation.special", "Special"],
  ["string", "String"],
  ["type", "Type"],
  ["variable", "Identifier"],
]

[language.go]
highlight-name-and-groups = [
  ["comment", "Comment"],
  ["constant.builtin", "Constant"],
  ["escape", "Delimiter"],
  ["function", "Function"],
  ["function.builtin", "Special"],
  ["function.method", "Include"],
  ["keyword", "Keyword"],
  ["number", "Number"],
  ["operator", "Operator"],
  ["property", "SpecialKey"],
  ["string", "String"],
  ["type", "Type"],
  ["variable", "Identifier"],
]

[language.markdown]
highlight-name-and-groups = [
  ["none", "Normal"],
  ["punctuation.delimiter", "Delimiter"],
  ["punctuation.special", "Special"],
  ["string.escape", "String"],
  ["text.literal", "SpecialChar"],
  ["text.reference", "Float"],
  ["text.title", "Title"],
  ["text.uri", "Directory"],
]

[language.rust]
highlight-name-and-groups = [
  ["attribute", "Special"],
  ["comment", "Comment"],
  ["constant", "Constant"],
  ["constant.builtin", "Constant"],
  ["constructor", "Tag"],
  ["escape", "Todo"],
  ["function", "Function"],
  ["function.macro", "Macro"],
  ["function.method", "SpecialKey"],
  ["keyword", "Keyword"],
  ["label", "Label"],
  ["operator", "Operator"],
  ["property", "Number"],
  ["punctuation.bracket", "Delimiter"],
  ["punctuation.delimiter", "Delimiter"],
  ["string", "String"],
  ["type", "Type"],
  ["type.builtin", "Type"],
  ["variable.builtin", "Identifier"],
  ["variable.parameter", "Identifier"],
]

[language.swift]
highlight-name-and-groups = [
  ["attribute", "Special"],
  ["comment", "Comment"],
  ["constant", "Constant"],
  ["constant.builtin", "Constant"],
  ["constructor", "Function"],
  ["function", "Function"],
  ["function.builtin", "Special"],
  ["function.method", "Function"],
  ["keyword", "Keyword"],
  ["number", "Number"],
  ["operator", "Operator"],
  ["property", "SpecialKey"],
  ["punctuation.bracket", "Delimiter"],
  ["punctuation.delimiter", "Delimiter"],
  ["string", "String"],
  ["type", "Type"],
  ["type.builtin", "Type"],
  ["variable", "Identifier"],
  ["variable.builtin", "Identifier"],
  ["variable.parameter", "Identifier"],
]

[language.viml]
highlight-name-and-groups = [
  ["_option", "StorageClass"],
  ["_scope", "Special"],
  ["boolean", "Boolean"],
  ["comment", "Comment"],
  ["conditional", "Conditional"],
  ["conditional.ternary", "Conditional"],
  ["constant", "Constant"],
  ["constant.builtin", "Constant"],
  ["exception", "Exception"],
  ["float", "Float"],
  ["function", "Function"],
  ["function.call", "Function"],
  ["function.macro", "Macro"],
  ["keyword", "Keyword"],
  ["keyword.function", "Keyword"],
  ["keyword.operator", "Keyword"],
  ["label", "Label"],
  ["namespace", "PreProc"],
  ["number", "Number"],
  ["operator", "Operator"],
  ["parameter", "Special"],
  ["property", "Identifier"],
  ["punctuation.bracket", "Delimiter"],
  ["punctuation.delimiter", "Delimiter"],
  ["punctuation.special", "Delimiter"],
  ["repeat", "Repeat"],
  ["spell", "SpellLocal"],
  ["string", "String"],
  ["string.regex", "Typedef"],
  ["string.special", "SpecialChar"],
  ["type", "Type"],
  ["variable", "Identifier"],
  ["variable.builtin", "Identifier"],
]
