[package]
name = "doc_gen"
version = "0.1.0"
edition = "2021"
description = "Generate config markdown document from the inline docs"

[dependencies]
inflections = "1.1.1"
maple_config = { path = "../" }
toml = "0.5"
syn = { version = "1", features = ["full"] }
quote = "1"
itertools = "0.12.0"
toml_edit = { version = "0.22.12", features = [ "parse" ] }
