[package]
name = "maple_cli"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2018"
license = "MIT"
publish = false
homepage = "https://github.com/liuchengxu/vim-clap"
description = "vim-clap external filter gadget"

[dependencies]
curl = "0.4.28"
log = "0.4"
log4rs = "0.12"
regex = "1"
rayon = "1.2"
serde = { package = "serde", version = "1.0",  features = ["derive"] }
reqwest = { version = "0.10", features = ["blocking"] }
anyhow = "1.0"
structopt = "0.3"
bytecount = "0.6"
itertools = "0.9"
serde_json = "1.0"
fuzzy-matcher = "0.3.1"
crossbeam-channel = "0.4"
tokio = { version = "0.2.20", features = ["fs"] }
indicatif = "0.14.0"

icon = { path = "../icon" }
pattern = { path = "../pattern" }
printer = { path = "../printer" }
fuzzy_filter = { path = "../fuzzy_filter" }
extracted_fzy = { path = "../extracted_fzy" }
