[package]
name = "filter"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
parking_lot = "0.12"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subprocess = { git = "https://github.com/hniksic/rust-subprocess" }
tracing = "0.1"

icon = { path = "../icon" }
matcher = { path = "../matcher" }
pattern = { path = "../pattern" }
printer = { path = "../printer" }
types = { path = "../types" }
utility = { path = "../utility" }
